config/routes.rb
Rails.application.routes.draw do
  resources :creditcards
  resources :users
  root 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creditcard.rb
class Creditcard < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, length: { maximum: 40 }, presence: true
  validates :email, length: { maximum: 45 }, presence: true
  validates :password, length: { maximum: 45 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "hello world!"
  end
end

app/controllers/creditcards_controller.rb
class CreditcardsController < ApplicationController
  before_action :set_creditcard, only: [:show, :edit, :update, :destroy]

  # GET /creditcards
  # GET /creditcards.json
  def index
    @creditcards = Creditcard.all
  end

  # GET /creditcards/1
  # GET /creditcards/1.json
  def show
  end

  # GET /creditcards/new
  def new
    @creditcard = Creditcard.new
  end

  # GET /creditcards/1/edit
  def edit
  end

  # POST /creditcards
  # POST /creditcards.json
  def create
    @creditcard = Creditcard.new(creditcard_params)

    respond_to do |format|
      if @creditcard.save
        format.html { redirect_to @creditcard, notice: 'Creditcard was successfully created.' }
        format.json { render :show, status: :created, location: @creditcard }
      else
        format.html { render :new }
        format.json { render json: @creditcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creditcards/1
  # PATCH/PUT /creditcards/1.json
  def update
    respond_to do |format|
      if @creditcard.update(creditcard_params)
        format.html { redirect_to @creditcard, notice: 'Creditcard was successfully updated.' }
        format.json { render :show, status: :ok, location: @creditcard }
      else
        format.html { render :edit }
        format.json { render json: @creditcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creditcards/1
  # DELETE /creditcards/1.json
  def destroy
    @creditcard.destroy
    respond_to do |format|
      format.html { redirect_to creditcards_url, notice: 'Creditcard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creditcard
      @creditcard = Creditcard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def creditcard_params
      params.require(:creditcard).permit(:network, :cardnumber, :name, :address, :country, :cvv, :exp, :user_id)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creditcards_helper.rb
module CreditcardsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/creditcards/_form.html.erb
<%= form_with(model: creditcard, local: true) do |form| %>
  <% if creditcard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(creditcard.errors.count, "error") %> prohibited this creditcard from being saved:</h2>

      <ul>
        <% creditcard.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :network %>
    <%= form.text_field :network %>
  </div>

  <div class="field">
    <%= form.label :cardnumber %>
    <%= form.text_field :cardnumber %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :cvv %>
    <%= form.number_field :cvv %>
  </div>

  <div class="field">
    <%= form.label :exp %>
    <%= form.text_field :exp %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/creditcards/edit.html.erb
<h1>Editing Creditcard</h1>

<%= render 'form', creditcard: @creditcard %>

<%= link_to 'Show', @creditcard %> |
<%= link_to 'Back', creditcards_path %>

app/views/creditcards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Creditcards</h1>

<table>
  <thead>
    <tr>
      <th>Network</th>
      <th>Cardnumber</th>
      <th>Name</th>
      <th>Address</th>
      <th>Country</th>
      <th>Cvv</th>
      <th>Exp</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @creditcards.each do |creditcard| %>
      <tr>
        <td><%= creditcard.network %></td>
        <td><%= creditcard.cardnumber %></td>
        <td><%= creditcard.name %></td>
        <td><%= creditcard.address %></td>
        <td><%= creditcard.country %></td>
        <td><%= creditcard.cvv %></td>
        <td><%= creditcard.exp %></td>
        <td><%= creditcard.user_id %></td>
        <td><%= link_to 'Show', creditcard %></td>
        <td><%= link_to 'Edit', edit_creditcard_path(creditcard) %></td>
        <td><%= link_to 'Destroy', creditcard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Creditcard', new_creditcard_path %>

app/views/creditcards/new.html.erb
<h1>New Creditcard</h1>

<%= render 'form', creditcard: @creditcard %>

<%= link_to 'Back', creditcards_path %>

app/views/creditcards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Network:</strong>
  <%= @creditcard.network %>
</p>

<p>
  <strong>Cardnumber:</strong>
  <%= @creditcard.cardnumber %>
</p>

<p>
  <strong>Name:</strong>
  <%= @creditcard.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @creditcard.address %>
</p>

<p>
  <strong>Country:</strong>
  <%= @creditcard.country %>
</p>

<p>
  <strong>Cvv:</strong>
  <%= @creditcard.cvv %>
</p>

<p>
  <strong>Exp:</strong>
  <%= @creditcard.exp %>
</p>

<p>
  <strong>User:</strong>
  <%= @creditcard.user_id %>
</p>

<%= link_to 'Edit', edit_creditcard_path(@creditcard) %> |
<%= link_to 'Back', creditcards_path %>

app/views/dashboard/index.html.erb
<body class="preview-page">
<div class="preview-bar bg-white fixed-top py-2 border-bottom-primary">
<div class="container-fluid h-100">
<div class="row align-items-center justify-content-between h-100">
<div class="col d-none d-lg-block">
 <ul class="nav responsive-toggler justify-content-center" role="tablist">
<li class="nav-item">
<a class="nav-link active" id="desktopToggle" data-toggle="tab" href="#" role="tab" aria-selected="true">
<i class="fal fa-desktop"></i>
</a>
</li>
<li class="nav-item">
<a class="nav-link" id="mobileToggle" data-toggle="tab" href="#" role="tab" aria-selected="false">
<i class="fal fa-mobile"></i>
</a>
</li>
</ul>
</div>
<div class="col text-right">
</div>
</div>
</div>
</div>
<iframe class="iframe-preview" width="100%" src="https://startbootstrap.github.io/startbootstrap-sb-admin-2/"></iframe>
<script id="dsq-count-scr" src="//startbootstrap.disqus.com/count.js" async type="40d7c29cabf936b459e4d21f-text/javascript"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous" type="40d7c29cabf936b459e4d21f-text/javascript"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous" type="40d7c29cabf936b459e4d21f-text/javascript"></script>
<script type="40d7c29cabf936b459e4d21f-text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.lazy/1.7.9/jquery.lazy.min.js"></script>
<script type="40d7c29cabf936b459e4d21f-text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.lazy/1.7.9/jquery.lazy.plugins.min.js"></script>
<script src="https://startbootstrap.com/assets/js/scripts.js" type="40d7c29cabf936b459e4d21f-text/javascript"></script>
<script type="40d7c29cabf936b459e4d21f-text/javascript">
        $("#desktopToggle").on('click', function(e) {
            e.preventDefault();
            $(".iframe-preview").removeClass("iframe-preview-mobile");
        });
        $("#mobileToggle").on('click', function(e) {
            e.preventDefault();
            $(".iframe-preview").addClass("iframe-preview-mobile");
        });
    </script>
<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="40d7c29cabf936b459e4d21f-|49" defer=""></script>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<script type="40d7c29cabf936b459e4d21f-text/javascript">
    var host = "startbootstrap.com";
    if ((host == window.location.host) && (window.location.protocol != "https:"))
      window.location.protocol = "https";
  </script>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="author" content="Start Bootstrap">
<meta name="google-site-verification" content="37Tru9bxB3NrqXCt6JT5Vx8wz2AJQ0G4TkC-j8WL3kw">

    <title>RTC Financial Group</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


<link rel="canonical" href="https://startbootstrap.com/previews/sb-admin-2/">

<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.12.0/css/all.css" integrity="sha384-ekOryaXPbeCpWQNxMwSWVvQ0+1VrStoPJq54shlYhR8HzQgig1v5fas6YgOqLoKz" crossorigin="anonymous">

<link rel="stylesheet" href="https://startbootstrap.com/assets/style-theme.css">

<link type="application/atom+xml" rel="alternate" href="https://startbootstrap.com/feed.xml" title="startbootstrap" />

<meta property="og:title" content="RTC Financial Group">
<meta property="og:site_name" content="Start Bootstrap">
<meta property="og:type" content="website">
<meta property="og:description" content="">
<meta property="og:image" content="https://startbootstrap.com/assets/img/branding/og-start-bootstrap.png">
<meta property="og:url" content="https://startbootstrap.com/previews/sb-admin-2/">
<meta property="og:image:alt" content="SB Admin 2 - Theme Preview">

<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://startbootstrap.com/assets/img/branding/start-bootstrap-logo-500x500.png">
<meta name="twitter:site" content="@SBootstrap">

<link rel="apple-touch-icon" sizes="180x180" href="https://startbootstrap.com/assets/img/icons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="https://startbootstrap.com/assets/img/icons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="https://startbootstrap.com/assets/img/icons/favicon-16x16.png">
<link rel="manifest" href="/assets/img/icons/site.webmanifest">
<link rel="mask-icon" href="/assets/img/icons/safari-pinned-tab.svg" color="#dd3d31">
<meta name="msapplication-TileColor" content="#dd3d31">
<meta name="theme-color" content="#ffffff">


  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>